####  1. ตรวจสอบว่ามี library ของ Numpy ถูกติดตั้งอยู่หรือไม่

In [1]:
!pip show numpy

#### 2. ถ้ายังไม่ได้ติดตั้งให้ทำการติดตั้ง library ของ numpy โดยใช้คำสั่ง

In [2]:
!pip install numpy

You should consider upgrading via the 'C:\Users\1000259375\Desktop\DE Project\PythonMLBasic\env\Scripts\python.exe -m pip install --upgrade pip' command.



     --------------------------------------- 15.8/15.8 MB 26.2 MB/s eta 0:00:00


#### 3. การสร้าง array ใน numpy โดย np.array()

In [6]:
import numpy as np

# array scalar 1D
a = np.array(10)
print(a)

# array vector
row = np.array([1,2,3]) # 1 row 3 columns
column = np.array([[1],[2],[3]]) # 3 rows 1 column

print(row)
print(column)

10
[1 2 3]
[[1]
 [2]
 [3]]


In [7]:
# matrix array
matrix = np.array([[1,2,3],[4,5,6]]) # 2 rows 3 cols
print(matrix)


[[1 2 3]
 [4 5 6]]


#### 4. การสร้างตัวเลขสุ่มใน numpy โดย np.randdom

In [8]:
# random integer 0-9 มา 5 ตัว
r1 = np.random.randint(0,10,5) # vector 1 row 5 cols
print(r1)

[6 1 1 3 4]


In [9]:
# random floar 0-1
r2 = np.random.random(5) # vector 1 row 5 cols
print(r2)

[0.6111893  0.69100802 0.815083   0.04217326 0.97806057]


#### 5. การเข้าถึงและเลือกสมาชิกใน array โดยใช้คำสั่ง

In [16]:
vrow = np.array([1,2,3,4,5,6,7,8,9,10]) # 1row 10 cols
print(vrow)
print(vrow[3])
print(vrow[2:6])
print(vrow[:5])
print(vrow[5:])
print(vrow[-3:-1])

[ 1  2  3  4  5  6  7  8  9 10]
4
[3 4 5 6]
[1 2 3 4 5]
[ 6  7  8  9 10]
[8 9]


#### 6. หาค่าทางสถิติโดยใช้ numpy

In [17]:
stat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(stat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# statistics
print("Max: ", np.max(stat))
print("Min: ", np.min(stat))
print("Mean: ", np.mean(stat))
print("Median: ", np.median(stat))
print("StdDev: ", np.std(stat))
print("Variance: ", np.var(stat))

Max:  12
Min:  1
Mean:  6.5
Median:  6.5
StdDev:  3.452052529534663
Variance:  11.916666666666666
